name: CI - Playwright

on:
  push:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # --- Run tests (failures will set exit code 1) ---
      - name: Run Playwright tests
        id: test
        run: |
          echo "Repo root:"
          pwd
          ls -la
          npx playwright test --reporter=html
        continue-on-error: false

      # --- Always collect artifacts, even if tests failed ---
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload test artifacts (videos/traces/screenshots)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results/**
            **/test-results/**
          retention-days: 7
